<?php

declare(strict_types=1);

namespace Josh\LaravelDoctor\Fixers;

use Josh\LaravelDoctor\Diagnostics\Diagnostic;
use Josh\LaravelDoctor\Scanner\ScanResult;

class ManualFixReportWriter
{
    /**
     * @param  array<int, string>  $unfixableRules
     */
    public function write(string $basePath, ScanResult $scanResult, array $unfixableRules): string
    {
        $unfixableLookup = array_fill_keys($unfixableRules, true);

        $manualDiagnostics = array_values(array_filter(
            $scanResult->diagnostics,
            static fn (Diagnostic $diagnostic): bool => isset($unfixableLookup[$diagnostic->rule])
        ));

        $reportsDirectory = rtrim($basePath, '/').'/.laravel-doctor';
        if (! is_dir($reportsDirectory)) {
            mkdir($reportsDirectory, 0755, true);
        }

        $filePath = $reportsDirectory.'/manual-fix-plan.md';

        file_put_contents($filePath, $this->buildReportContents($manualDiagnostics, $unfixableRules));

        return $filePath;
    }

    /**
     * @param  array<int, Diagnostic>  $manualDiagnostics
     * @param  array<int, string>  $unfixableRules
     */
    private function buildReportContents(array $manualDiagnostics, array $unfixableRules): string
    {
        $lines = [
            '# Laravel Doctor Manual Fix Plan',
            '',
            'Generated by `php artisan doctor:fix` when some diagnostics could not be fixed programmatically.',
            '',
            '## Prompt To Paste Into Your Agent',
            '',
            '```text',
            'I need you to manually fix unresolved Laravel Doctor diagnostics in my codebase.',
            'Work through the checklist in `.laravel-doctor/manual-fix-plan.md` and apply changes file by file.',
            'Prioritize correctness and performance issues first, then maintainability issues.',
            'When finished, run `php artisan doctor` and summarize score changes and remaining findings.',
            '```',
            '',
            '## Unfixable Rules',
            '',
        ];

        foreach ($unfixableRules as $ruleId) {
            $lines[] = '- `'.$ruleId.'`';
        }

        $lines[] = '';
        $lines[] = '## Checklist';
        $lines[] = '';

        $groupedByRule = [];

        foreach ($manualDiagnostics as $diagnostic) {
            $groupedByRule[$diagnostic->rule][] = $diagnostic;
        }

        foreach ($groupedByRule as $ruleId => $diagnostics) {
            $firstDiagnostic = $diagnostics[0];

            $lines[] = '### `'.$ruleId.'`';
            $lines[] = '';
            $lines[] = '- Guidance: '.$firstDiagnostic->help;
            $lines[] = '';

            foreach ($diagnostics as $diagnostic) {
                $location = $diagnostic->line > 0
                    ? sprintf('%s:%d', $diagnostic->file, $diagnostic->line)
                    : $diagnostic->file;

                $lines[] = '- [ ] `'.$location.'` — '.$diagnostic->message;
            }

            $lines[] = '';
        }

        return implode("\n", $lines)."\n";
    }
}
